package types

type City []struct {
	Name       string `json:"name"`
	LocalNames struct {
		Co          string `json:"co"`
		Kg          string `json:"kg"`
		So          string `json:"so"`
		Bg          string `json:"bg"`
		Oc          string `json:"oc"`
		Hy          string `json:"hy"`
		Sw          string `json:"sw"`
		Jv          string `json:"jv"`
		Sh          string `json:"sh"`
		Nl          string `json:"nl"`
		Vi          string `json:"vi"`
		Is          string `json:"is"`
		It          string `json:"it"`
		Nb          string `json:"nb"`
		Bo          string `json:"bo"`
		Li          string `json:"li"`
		An          string `json:"an"`
		Lg          string `json:"lg"`
		Uz          string `json:"uz"`
		Nn          string `json:"nn"`
		Tr          string `json:"tr"`
		Av          string `json:"av"`
		My          string `json:"my"`
		Ln          string `json:"ln"`
		Hu          string `json:"hu"`
		Kw          string `json:"kw"`
		Pl          string `json:"pl"`
		Ak          string `json:"ak"`
		Se          string `json:"se"`
		Sk          string `json:"sk"`
		Mr          string `json:"mr"`
		Ku          string `json:"ku"`
		Fo          string `json:"fo"`
		Ch          string `json:"ch"`
		Na          string `json:"na"`
		Dz          string `json:"dz"`
		Su          string `json:"su"`
		De          string `json:"de"`
		El          string `json:"el"`
		Tt          string `json:"tt"`
		Be          string `json:"be"`
		Mi          string `json:"mi"`
		Fa          string `json:"fa"`
		Ka          string `json:"ka"`
		Ro          string `json:"ro"`
		He          string `json:"he"`
		Te          string `json:"te"`
		Lt          string `json:"lt"`
		Iu          string `json:"iu"`
		Ja          string `json:"ja"`
		Ky          string `json:"ky"`
		Br          string `json:"br"`
		Dv          string `json:"dv"`
		Zu          string `json:"zu"`
		Ca          string `json:"ca"`
		Vo          string `json:"vo"`
		Hi          string `json:"hi"`
		Fr          string `json:"fr"`
		Ta          string `json:"ta"`
		Mt          string `json:"mt"`
		Ay          string `json:"ay"`
		Ms          string `json:"ms"`
		Ps          string `json:"ps"`
		Kn          string `json:"kn"`
		Th          string `json:"th"`
		Fy          string `json:"fy"`
		Tl          string `json:"tl"`
		Ug          string `json:"ug"`
		Io          string `json:"io"`
		Am          string `json:"am"`
		Tk          string `json:"tk"`
		Ab          string `json:"ab"`
		Cs          string `json:"cs"`
		Gl          string `json:"gl"`
		Wa          string `json:"wa"`
		Kk          string `json:"kk"`
		ID          string `json:"id"`
		Os          string `json:"os"`
		La          string `json:"la"`
		Mn          string `json:"mn"`
		Ia          string `json:"ia"`
		Za          string `json:"za"`
		Wo          string `json:"wo"`
		Bi          string `json:"bi"`
		Sr          string `json:"sr"`
		Pt          string `json:"pt"`
		FeatureName string `json:"feature_name"`
		Ur          string `json:"ur"`
		Ko          string `json:"ko"`
		Ar          string `json:"ar"`
		Lv          string `json:"lv"`
		Ml          string `json:"ml"`
		Gn          string `json:"gn"`
		Ba          string `json:"ba"`
		Ru          string `json:"ru"`
		Es          string `json:"es"`
		Bs          string `json:"bs"`
		Fi          string `json:"fi"`
		Eu          string `json:"eu"`
		St          string `json:"st"`
		Et          string `json:"et"`
		Cy          string `json:"cy"`
		Sv          string `json:"sv"`
		Sm          string `json:"sm"`
		Zh          string `json:"zh"`
		Bn          string `json:"bn"`
		Sl          string `json:"sl"`
		Az          string `json:"az"`
		Qu          string `json:"qu"`
		Eo          string `json:"eo"`
		Yo          string `json:"yo"`
		Ie          string `json:"ie"`
		Ce          string `json:"ce"`
		Kv          string `json:"kv"`
		Mk          string `json:"mk"`
		ASCII       string `json:"ascii"`
		Yi          string `json:"yi"`
		Kl          string `json:"kl"`
		Hr          string `json:"hr"`
		Mg          string `json:"mg"`
		Ga          string `json:"ga"`
		Gv          string `json:"gv"`
		Da          string `json:"da"`
		Ss          string `json:"ss"`
		Af          string `json:"af"`
		Ty          string `json:"ty"`
		Sg          string `json:"sg"`
		En          string `json:"en"`
		Ht          string `json:"ht"`
		Sc          string `json:"sc"`
		Cv          string `json:"cv"`
		Sq          string `json:"sq"`
		Gd          string `json:"gd"`
		Uk          string `json:"uk"`
		Tg          string `json:"tg"`
		Cu          string `json:"cu"`
		No          string `json:"no"`
	} `json:"local_names,omitempty"`
	Lat         float64 `json:"lat"`
	Lon         float64 `json:"lon"`
	Country     string  `json:"country"`
	State       string  `json:"state"`
	LocalNames0 struct {
		En string `json:"en"`
		Ru string `json:"ru"`
	} `json:"local_names,omitempty"`
}
